-   id: format-sql
    name: format-sql
    entry: format-sql
    language: python
    files: \.sql$
-   id: sqlformat
    name: sqlformat
    entry: sqlformat-inplace
    language: python
    files: \.sql$
